const AllocationToolPage = () => {
	return (<div>AllocationToolPage
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
		<div>Space</div>
	</div>);
};

export default AllocationToolPage;
